// Code generated by "stringer -type=AssemblyInstructionType -linecomment=false"; DO NOT EDIT.

package MOS6510

import "strconv"

const _AssemblyInstructionType_name = "UNDEFADCANDASLBCCBCSBEQBITBMIBNEBPLBRKBVCBVSCLCCLDCLICLVCMPCPXCPYDECDEXDEYEORINCINXINYJMPJSRLDALDXLDYLSRNOPORAPHAPHPPLAPLPROLRORRTIRTSSBCSECSEDSEISTASTXSTYTAXTAYTSXTXATXSTYA"

var _AssemblyInstructionType_index = [...]uint8{0, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98, 101, 104, 107, 110, 113, 116, 119, 122, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167, 170, 173}

func (i AssemblyInstructionType) String() string {
	i -= 1
	if i < 0 || i >= AssemblyInstructionType(len(_AssemblyInstructionType_index)-1) {
		return "AssemblyInstructionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AssemblyInstructionType_name[_AssemblyInstructionType_index[i]:_AssemblyInstructionType_index[i+1]]
}
